#!/bin/bash

case "$1" in
    purge)
	rm -rf /var/run/kikori
	rm -rf /var/log/kikori
	userdel kikori > /dev/null 2>&1	
	;;
    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
	;;
esac

exit 0
